'''
Neuron simulator export for:

Components:
    null (Type: notes)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    Input_4 (Type: pulseGenerator:  delay=0.02 (SI time) duration=0.06 (SI time) amplitude=8.000000000000001E-11 (SI current))
    Default_Simulation_Configuration (Type: networkWithTemperature:  temperature=279.45 (SI temperature))
    null (Type: notes)
    ar (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    ar__m00_25 (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    cad (Type: fixedFactorConcentrationModelTraub:  restingConc=0.0 (SI concentration) beta=10.0 (SI per_time) phi=2.6E15 (SI rho_factor))
    null (Type: notes)
    cad__beta0_03__phi300000 (Type: fixedFactorConcentrationModelTraub:  restingConc=0.0 (SI concentration) beta=30.0 (SI per_time) phi=3.0E16 (SI rho_factor))
    null (Type: notes)
    cal (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    cat (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    cat_a (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    k2 (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    ka (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    ka_ib (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    kahp (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    kahp_deeppyr (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    kahp_slower (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    kc (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    kc_fast (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    kdr (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    kdr_fs (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    km (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    naf (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    naf2 (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    naf_tcr (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    nap (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    napf (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    napf_spinstell (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    napf_tcr (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    pas (Type: ionChannelPassive:  conductance=1.0E-11 (SI conductance))
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    null (Type: include)
    TestSeg_all (Type: cell)
    Sim_Default_Simulation_Configuration (Type: Simulation:  length=0.1 (SI time) step=5.0E-6 (SI time))


    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.4.5
         org.neuroml.model   v1.4.5
         jLEMS               v0.9.8.5

'''

import neuron

import time
h = neuron.h
h.load_file("stdlib.hoc")

h.load_file("stdgui.hoc")

h("objref p")
h("p = new PythonObject()")

class NeuronSimulation():

    def __init__(self, tstop, dt):

        # Adding simulation Component(id=Sim_Default_Simulation_Configuration type=Simulation) of network/component: Default_Simulation_Configuration (Type: networkWithTemperature:  temperature=279.45 (SI temperature))

        # Temperature used for network: 279.45 K
        h.celsius = 279.45 - 273.15

        print("Population CG_CML contains 1 instance(s) of component: TestSeg_all of type: cell")

        print("Setting the default initial concentrations for ca (used in TestSeg_all) to 0.01 mM (internal), 2.0 mM (external)")
        h("cai0_ca_ion = 0.01")
        h("cao0_ca_ion = 2.0")

        h.load_file("TestSeg_all.hoc")
        a_CG_CML = []
        h("n_CG_CML = 1")
        h("objectvar a_CG_CML[n_CG_CML]")
        for i in range(int(h.n_CG_CML)):
            h("a_CG_CML[%i] = new TestSeg_all()"%i)
            h("access a_CG_CML[%i].Soma"%i)

        h("a_CG_CML[0].position(54.987994999999998, 27.486060999999999, 40.31429)")

        h("proc initialiseV_CG_CML() { for i = 0, n_CG_CML-1 { a_CG_CML[i].set_initial_v() } }")
        h("objref fih_CG_CML")
        h('{fih_CG_CML = new FInitializeHandler(0, "initialiseV_CG_CML()")}')

        h("proc initialiseIons_CG_CML() { for i = 0, n_CG_CML-1 { a_CG_CML[i].set_initial_ion_properties() } }")
        h("objref fih_ion_CG_CML")
        h('{fih_ion_CG_CML = new FInitializeHandler(1, "initialiseIons_CG_CML()")}')

        # Adding input: Component(id=0 type=input)

        h("objref Input_4_0")
        h("a_CG_CML[0].Soma { Input_4_0 = new Input_4(0.500000) } ")

        trec = h.Vector()
        trec.record(h._ref_t)

        h.tstop = tstop

        h.dt = dt

        h.steps_per_ms = 1/h.dt



        # File to save: time
        # Column: time
        h(' objectvar v_time ')
        h(' { v_time = new Vector() } ')
        h(' v_time.record(&t) ')
        h.v_time.resize((h.tstop * h.steps_per_ms) + 1)

        # File to save: Volts_file__CG_CML
        # Column: CG_CML/0/TestSeg_all/v
        h(' objectvar v_v_CG_CML_0_TestSeg_all_v_Volts_file__CG_CML ')
        h(' { v_v_CG_CML_0_TestSeg_all_v_Volts_file__CG_CML = new Vector() } ')
        h(' v_v_CG_CML_0_TestSeg_all_v_Volts_file__CG_CML.record(&a_CG_CML[0].Soma.v(0.5)) ')
        h.v_v_CG_CML_0_TestSeg_all_v_Volts_file__CG_CML.resize((h.tstop * h.steps_per_ms) + 1)



    def run(self):

        sim_start = time.time()
        print("Running a simulation of %sms (dt = %sms)" % (h.tstop, h.dt))

        h.run()

        sim_end = time.time()
        sim_time = sim_end - sim_start
        print("Finished simulation in %f seconds (%f mins), saving results..."%(sim_time, sim_time/60.0))


        # File to save: time
        py_v_time = [ t/1000 for t in h.v_time.to_python() ]  # Convert to Python list for speed...

        f_time_f2 = open('time.dat', 'w')
        for i in range(int(h.tstop * h.steps_per_ms) + 1):
            f_time_f2.write('%f'% py_v_time[i])  # Save in SI units...+ '\n')
        f_time_f2.close()
        print("Saved data to: time.dat")

        # File to save: Volts_file__CG_CML
        py_v_v_CG_CML_0_TestSeg_all_v_Volts_file__CG_CML = [ float(x  / 1000.0) for x in h.v_v_CG_CML_0_TestSeg_all_v_Volts_file__CG_CML.to_python() ]  # Convert to Python list for speed, variable has dim: voltage

        f_Volts_file__CG_CML_f2 = open('Sim_Default_Simulation_Configuration.CG_CML.v.dat', 'w')
        for i in range(int(h.tstop * h.steps_per_ms) + 1):
            f_Volts_file__CG_CML_f2.write('%e\t'% py_v_time[i]  + '%e\t'%(py_v_v_CG_CML_0_TestSeg_all_v_Volts_file__CG_CML[i]) + '\n')
        f_Volts_file__CG_CML_f2.close()
        print("Saved data to: Sim_Default_Simulation_Configuration.CG_CML.v.dat")

        save_end = time.time()
        save_time = save_end - sim_end
        print("Finished saving results in %f seconds"%(save_time))

        print("Done")

        quit()
if __name__ == '__main__':

    ns = NeuronSimulation(tstop=100, dt=0.005)

    ns.run()

