TITLE Mod file for component: Component(id=Syn_GABAA_SupBask_SupLTS type=expOneSynapse)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.5.0
         org.neuroml.model   v1.5.0
         jLEMS               v0.9.8.7

ENDCOMMENT

NEURON {
    POINT_PROCESS Syn_GABAA_SupBask_SupLTS
    RANGE tauDecay                          : parameter
    RANGE gbase                             : parameter
    RANGE erev                              : parameter
    
    RANGE i                                 : exposure
    
    
    NONSPECIFIC_CURRENT i 
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (S) = (siemens)
    
}

PARAMETER {
    
    tauDecay = 3 (ms)
    gbase = 4.9999997E-4 (uS)
    erev = -75 (mV)
}

ASSIGNED {
    ? Standard Assigned variables with baseSynapse
    v (mV)
    celsius (degC)
    temperature (K)
    
    i (nA)                                 : derived variable
    rate_g (uS/ms)
    
}

STATE {
    g (uS) 
    
}

INITIAL {
    temperature = celsius + 273.15
    
    rates()
    rates() ? To ensure correct initialisation.
    
    g = 0
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    
    
}

NET_RECEIVE(weight) {
    ?state_discontinuity(g, g  + (weight *   gbase  )) : From Syn_GABAA_SupBask_SupLTS
    g = g  + (weight *   gbase  ) : From Syn_GABAA_SupBask_SupLTS
    
}

DERIVATIVE states {
    rates()
    g' = rate_g 
    
}

PROCEDURE rates() {
    
    i = -1 * g  * (  erev   - v) ? evaluable
    rate_g = -  g   /  tauDecay ? Note units of all quantities used here need to be consistent!
    
     
    
}

